displayName=Click Output
author=Johndavis2021
description=Logs interaction text to chatbox with a customizable prefix
tags=debug,ui,logging
version=
plugins=com.ClickOutput.ClickOutputPlugin
build=standard